image: rustlang/rust:nightly

default:
  before_script:
    - rustc --version 
    - cargo --version

stages:
  - build

x86_64-unknown-linux-gnu:
  stage: build

  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/uad

  script:
    - cargo build --release --target x86_64-unknown-linux-gnu

x86_64-pc-windows-gnu:
  stage: build

  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/uad.exe

  script:
    - cargo build --release --target x86_64-pc-windows-gnu

