image: rustlang/rust:nightly-bullseye

default:
  before_script:
    - rustc --version 
    - cargo --version

stages:
  - build

i686-pc-windows-gnu:
  stage: build

  before_script:
    - apt update -yqq && apt install -yqq mingw-w64
    - rustup target add i686-pc-windows-gnu

  script:
    - cargo build --features glow --release --target i686-pc-windows-gnu
    - mv target/i686-pc-windows-gnu/release/uad_gui.exe target/i686-pc-windows-gnu/release/uad_gui-opengl.exe

  artifacts:
    paths:
      - target/i686-pc-windows-gnu/release/uad_gui-opengl.exe

x86_64-pc-windows-gnu:
  stage: build

  before_script:
    - apt update -yqq && apt install -yqq mingw-w64
    - rustup target add x86_64-pc-windows-gnu

  script:
    - cargo build --features glow --release --target x86_64-pc-windows-gnu
    - mv target/x86_64-pc-windows-gnu/release/uad_gui.exe target/x86_64-pc-windows-gnu/release/uad_gui-opengl.exe
    - cargo build --features wgpu --release --target x86_64-pc-windows-gnu

  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/uad_gui.exe
      - target/x86_64-pc-windows-gnu/release/uad_gui-opengl.exe

x86_64-unknown-linux-gnu:
  stage: build

  before_script:
    - apt update -yqq && apt install -yqq libxkbcommon-dev lld

  script:
    - cargo build --features glow --release --target x86_64-unknown-linux-gnu
    - mv target/x86_64-unknown-linux-gnu/release/uad_gui target/x86_64-unknown-linux-gnu/release/uad_gui-opengl
    - cargo build --features wgpu --release --target x86_64-unknown-linux-gnu

  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/uad_gui
      - target/x86_64-unknown-linux-gnu/release/uad_gui-opengl
