[package]
name = "UadGui"
version = "0.1.0"
authors = ["w1nst0n"]
edition = "2018"

[dependencies]
iced = { version = "^0.3", features = ["svg"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
static_init = "^1.0"

[profile.release]
opt-level = "s"
lto = true