cargo-features = ["strip"] # nightly

[package]
name = "uad_gui"
version = "0.1.0"
authors = ["w1nst0n"]
edition = "2021"

[features]
default = []
wgpu = ["iced/svg"] # iced/wgpu is default
glow = ["iced/glow"] # OpenGL support

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
static_init = "^1.0"
fern = { version = "^0.6", features = ["colored"] }
log = "^0.4"
chrono = "^0.4"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"