cargo-features = ["strip"] # nightly

[package]
name = "UadGui"
version = "0.1.0"
authors = ["w1nst0n"]
edition = "2018"
resolver = "2"

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", features = ["svg"] }
web-sys = { version = "0.3.51" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
static_init = "^1.0"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"
